query ListMedicines @auth(level: PUBLIC) {
  medicines {
    id
    slug
    genericName
    chemicalName
    category
    strength
    ageGroup
    prescriptionRequired
    verified
    maxDailyDoseAdults
    safetyPregnancy
    safetyBreastfeeding
    safetyElderly
    safetyChildren
    brandNames
    form
    createdDate
    imageUrl
    
    dosageRows_on_medicine {
      id
      ageGroup
      dose
      frequency
      maxPerDay
    }
    
    drugInteractions_on_medicine {
      id
      drug
      note
    }

    medicineVerifications_on_medicine {
      id
      doctorId
      slmcRegNo
      verifiedAt
    }
    
    medicineLocalizedContents_on_medicine {
      id
      language
      description
      howItWorks
      dosageNotes
      usedFor
      sideEffectsCommon
      sideEffectsLessCommon
      sideEffectsSerious
      
      warningCards_on_localizedContent {
        id
        title
        severity
        text
      }
    }
  }
}
query GetMedicineBySlug($slug: String!) @auth(level: PUBLIC) {
  medicines(where: {slug: {eq: $slug}}) {
    id
    slug
    genericName
    chemicalName
    category
    strength
    ageGroup
    prescriptionRequired
    verified
    maxDailyDoseAdults
    safetyPregnancy
    safetyBreastfeeding
    safetyElderly
    safetyChildren
    brandNames
    form
    createdDate
    imageUrl
    dosageRows_on_medicine {
      id
      ageGroup
      dose
      frequency
      maxPerDay
    }
    
    drugInteractions_on_medicine {
      id
      drug
      note
    }

    medicineVerifications_on_medicine {
      id
      doctorId
      slmcRegNo
      verifiedAt
    }
    
    medicineLocalizedContents_on_medicine {
      id
      language
      description
      howItWorks
      dosageNotes
      usedFor
      sideEffectsCommon
      sideEffectsLessCommon
      sideEffectsSerious
      
      warningCards_on_localizedContent {
        id
        title
        severity
        text
      }
    }
  }
}


query ListStaffAccounts @auth(level: PUBLIC) {
  staffAccounts {
    id
    firebaseUid
    email
    name
    profession
    slmcRegNo
    proofUrl
    status
    hospital
    specialization
    createdAt
  }
}

query GetStaffAccountByFirebaseUid($firebaseUid: String!) @auth(level: PUBLIC) {
  staffAccounts(where: { firebaseUid: { eq: $firebaseUid } }) {
    id
    firebaseUid
    email
    name
    profession
    slmcRegNo
    proofUrl
    status
    hospital
    specialization
    createdAt
  }
}
