extend type DosageRow {
  """
  ✨ Implicit foreign key field based on `DosageRow`.`medicine`. It must match the value of `Medicine`.`id`. See `@ref` for how to customize it.
  """
  medicineId: UUID! @fdc_generated(from: "DosageRow.medicine", purpose: IMPLICIT_REF_FIELD)
}
extend type DrugInteraction {
  """
  ✨ Implicit foreign key field based on `DrugInteraction`.`medicine`. It must match the value of `Medicine`.`id`. See `@ref` for how to customize it.
  """
  medicineId: UUID! @fdc_generated(from: "DrugInteraction.medicine", purpose: IMPLICIT_REF_FIELD)
}
extend type MedicineLocalizedContent {
  """
  ✨ Implicit foreign key field based on `MedicineLocalizedContent`.`medicine`. It must match the value of `Medicine`.`id`. See `@ref` for how to customize it.
  """
  medicineId: UUID! @fdc_generated(from: "MedicineLocalizedContent.medicine", purpose: IMPLICIT_REF_FIELD)
}
extend type MedicineVerification {
  """
  ✨ Implicit foreign key field based on `MedicineVerification`.`medicine`. It must match the value of `Medicine`.`id`. See `@ref` for how to customize it.
  """
  medicineId: UUID! @fdc_generated(from: "MedicineVerification.medicine", purpose: IMPLICIT_REF_FIELD)
}
extend type WarningCard {
  """
  ✨ Implicit foreign key field based on `WarningCard`.`localizedContent`. It must match the value of `MedicineLocalizedContent`.`id`. See `@ref` for how to customize it.
  """
  localizedContentId: UUID! @fdc_generated(from: "WarningCard.localizedContent", purpose: IMPLICIT_REF_FIELD)
}
