extend type Query {
  """
  ✨ Look up a single `DosageRow` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  dosageRow(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DosageRow_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DosageRow_FirstRow
  ): DosageRow @fdc_generated(from: "DosageRow", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `DrugInteraction` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  drugInteraction(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DrugInteraction_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DrugInteraction_FirstRow
  ): DrugInteraction @fdc_generated(from: "DrugInteraction", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Medicine` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  medicine(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Medicine_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Medicine_FirstRow
  ): Medicine @fdc_generated(from: "Medicine", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `MedicineLocalizedContent` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  medicineLocalizedContent(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MedicineLocalizedContent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MedicineLocalizedContent_FirstRow
  ): MedicineLocalizedContent @fdc_generated(from: "MedicineLocalizedContent", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `MedicineVerification` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  medicineVerification(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MedicineVerification_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MedicineVerification_FirstRow
  ): MedicineVerification @fdc_generated(from: "MedicineVerification", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `StaffAccount` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  staffAccount(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: StaffAccount_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StaffAccount_FirstRow
  ): StaffAccount @fdc_generated(from: "StaffAccount", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `WarningCard` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  warningCard(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WarningCard_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WarningCard_FirstRow
  ): WarningCard @fdc_generated(from: "WarningCard", purpose: QUERY_SINGLE)
  """
  ✨ List `DosageRow` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  dosageRows(
    """
    Filter condition to narrow down the query results.
    """
    where: DosageRow_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DosageRow_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DosageRow_Having
  ): [DosageRow!]! @fdc_generated(from: "DosageRow", purpose: QUERY_MULTIPLE)
  """
  ✨ List `DrugInteraction` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  drugInteractions(
    """
    Filter condition to narrow down the query results.
    """
    where: DrugInteraction_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DrugInteraction_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DrugInteraction_Having
  ): [DrugInteraction!]! @fdc_generated(from: "DrugInteraction", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Medicine` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  medicines(
    """
    Filter condition to narrow down the query results.
    """
    where: Medicine_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Medicine_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Medicine_Having
  ): [Medicine!]! @fdc_generated(from: "Medicine", purpose: QUERY_MULTIPLE)
  """
  ✨ List `MedicineLocalizedContent` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  medicineLocalizedContents(
    """
    Filter condition to narrow down the query results.
    """
    where: MedicineLocalizedContent_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [MedicineLocalizedContent_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: MedicineLocalizedContent_Having
  ): [MedicineLocalizedContent!]! @fdc_generated(from: "MedicineLocalizedContent", purpose: QUERY_MULTIPLE)
  """
  ✨ List `MedicineVerification` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  medicineVerifications(
    """
    Filter condition to narrow down the query results.
    """
    where: MedicineVerification_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [MedicineVerification_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: MedicineVerification_Having
  ): [MedicineVerification!]! @fdc_generated(from: "MedicineVerification", purpose: QUERY_MULTIPLE)
  """
  ✨ List `StaffAccount` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  staffAccounts(
    """
    Filter condition to narrow down the query results.
    """
    where: StaffAccount_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [StaffAccount_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: StaffAccount_Having
  ): [StaffAccount!]! @fdc_generated(from: "StaffAccount", purpose: QUERY_MULTIPLE)
  """
  ✨ List `WarningCard` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  warningCards(
    """
    Filter condition to narrow down the query results.
    """
    where: WarningCard_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [WarningCard_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: WarningCard_Having
  ): [WarningCard!]! @fdc_generated(from: "WarningCard", purpose: QUERY_MULTIPLE)
}
